name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: apt install mesa-common-dev libx11-dev libxfixes-dev libxcomposite-dev gcc g++ make
    
    - name: Build
      run: make

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
