name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: wget http://launchpadlibrarian.net/365941753/libgtk-3-dev_3.22.30-1ubuntu1_i386.deb && chmod +x libgtk-3-dev_3.22.30-1ubuntu1_i386.deb && sudo apt install ./libgtk-3-dev_3.22.30-1ubuntu1_i386.deb && sudo apt install mesa-common-dev libx11-dev libxfixes-dev libxcomposite-dev gcc g++ make
    
    - name: Build
      run: make
